from __future__ import annotations


DEVICES = [
    {"id": "mk3-5", "kind": "mk3_5", "name": "PRUSA MK3.5", "mentors": "Jakob Weiss, Dave", "type_label": "MK3.5", "sort_order": 1},
    {"id": "mini-alpha-1", "kind": "mini", "name": "PRUSA MINI+ (Alpha) 1", "mentors": "Jakob Weiss, Dave", "type_label": "MINI+", "sort_order": 2},
    {"id": "mini-beta-2", "kind": "mini", "name": "PRUSA MINI+ (Beta) 2", "mentors": "Jakob Weiss, Dave", "type_label": "MINI+", "sort_order": 3},
    {"id": "mini-gamma-3", "kind": "mini", "name": "PRUSA MINI+ (Gamma) 3", "mentors": "Jakob Weiss, Dave", "type_label": "MINI+", "sort_order": 4},
    {"id": "mini-delta-4", "kind": "mini", "name": "PRUSA MINI+ (Delta) 4", "mentors": "Jakob Weiss, Dave", "type_label": "MINI+", "sort_order": 5},
    {"id": "mini-epsilon-5", "kind": "mini", "name": "PRUSA MINI+ (Epsilon) 5", "mentors": "Jakob Weiss, Dave", "type_label": "MINI+", "sort_order": 6},
    {"id": "xl-5-tool", "kind": "xl5", "name": "PRUSA XL 5-Tool / 5-Nozzle", "mentors": "Jakob Weiss, Dave", "type_label": "XL 5-Tool", "sort_order": 7},
]


TASKS = [
    {"id": "bed-scraps", "applies_to": "all", "title": "Druckbett von Druckresten reinigen", "details": "Druckplatte nicht mit der Haut beruehren.", "level": "B", "interval_text": "vor jedem Druck", "cadence_days": None, "cadence_hours": None, "sort_order": 10},
    {"id": "plate-ipa", "applies_to": "all", "title": "Druckplatte mit Isopropanol reinigen", "details": "Nur bei kaltem Druckbett.", "level": "E", "interval_text": "2x im Monat, b.B.", "cadence_days": 15, "cadence_hours": None, "sort_order": 20},
    {"id": "nozzle-brush", "applies_to": "all", "title": "Nozzle mit Bronzezahnbuerste reinigen", "details": "Bei vorgeheiztem Hotend auch seitliche Flaechen reinigen.", "level": "E", "interval_text": "2x im Monat, b.B.", "cadence_days": 15, "cadence_hours": None, "sort_order": 30},
    {"id": "first-layer", "applies_to": "all", "title": "First-Layer-Calibration", "details": "Haftung der ersten Schicht prüfen und richtiges Profil auswählen.", "level": "E", "interval_text": "b.B.", "cadence_days": None, "cadence_hours": None, "sort_order": 40},
    {"id": "deep-bed-clean", "applies_to": "all", "title": "Eingehende Reinigung des Druckbetts", "details": "Smooth PEI: Wasser/Spuelmittel, ggf. Aceton. Textured: warmes Wasser/Spuelmittel.", "level": "M", "interval_text": "b.B., Herstellerangaben beachten", "cadence_days": None, "cadence_hours": None, "sort_order": 50},
    {"id": "software-update-mk3", "applies_to": "mk3_5", "title": "Firmware und Software prüfen", "details": "Prusa MK3.5 Firmware und passenden PrusaSlicer verwenden.", "level": "M", "interval_text": "1x im Monat, b.B.", "cadence_days": 30, "cadence_hours": None, "sort_order": 60},
    {"id": "software-update-mini", "applies_to": "mini", "title": "Firmware und Software prüfen", "details": "Prusa MINI+ Firmware und passenden PrusaSlicer verwenden.", "level": "M", "interval_text": "1x im Monat, b.B.", "cadence_days": 30, "cadence_hours": None, "sort_order": 60},
    {"id": "software-update-xl", "applies_to": "xl5", "title": "Firmware und Software prüfen", "details": "XL Firmware, PrusaSlicer und G-Code-Kompatibilität prüfen.", "level": "M", "interval_text": "1x im Monat, b.B.", "cadence_days": 30, "cadence_hours": None, "sort_order": 60},
    {"id": "axes-lube", "applies_to": "all", "title": "Achsen schmieren und kontrollieren", "details": "Nur Original-/geeignetes Schmiermittel verwenden; Achsen auf Defekte prüfen.", "level": "M", "interval_text": "200-300 Druckstunden oder 2x im Jahr", "cadence_days": 183, "cadence_hours": 250, "sort_order": 80},
    {"id": "extruder-clean", "applies_to": "all", "title": "Extruder reinigen und rekalibrieren", "details": "Zahnräder, Filamentsensor und Lüfter reinigen/prüfen.", "level": "M", "interval_text": "200-300 Druckstunden oder 2x im Jahr", "cadence_days": 183, "cadence_hours": 250, "sort_order": 90},
    {"id": "belts", "applies_to": "all", "title": "Riemenspannung prüfen", "details": "Selbsttest ausführen; bei kritischen Werten Riemen neu spannen.", "level": "M", "interval_text": "200-300 Druckstunden oder 2x im Jahr", "cadence_days": 183, "cadence_hours": 250, "sort_order": 100},
    {"id": "nozzle-change", "applies_to": "all", "title": "Nozzle tauschen", "details": "Nozzle-Tausch-Routine verwenden und danach First-Layer-Cal. ausfuehren.", "level": "M", "interval_text": "2x im Jahr, b.B.", "cadence_days": 183, "cadence_hours": None, "sort_order": 110},
    {"id": "xl-linear-rails", "applies_to": "xl5", "title": "XL Linear-Rails reinigen/schmieren", "details": "Geeignetes Linear-Rail-Schmiermittel verwenden, keine ungeeigneten Entfetter.", "level": "M", "interval_text": "alle 3-6 Monate", "cadence_days": 120, "cadence_hours": None, "sort_order": 120},
    {"id": "xl-z-leadscrews", "applies_to": "xl5", "title": "XL Z-Spindeln reinigen/schmieren", "details": "Nach ca. 500 Druckstunden reinigen und mit Prusa-Lubricant schmieren.", "level": "M", "interval_text": "ca. 500 Druckstunden", "cadence_days": None, "cadence_hours": 500, "sort_order": 130},
    {"id": "xl-corexy-belts", "applies_to": "xl5", "title": "XL CoreXY-Riemen prüfen", "details": "XY-Riemen auf Spannung, Abrieb und sauberen Lauf prüfen.", "level": "M", "interval_text": "200-300 Druckstunden, b.B.", "cadence_days": None, "cadence_hours": 250, "sort_order": 140},
    {"id": "xl-side-filament-sensor", "applies_to": "xl5", "title": "XL seitliche Filamentsensoren reinigen", "details": "Staub und Filamentreste aus Sensorbereichen entfernen.", "level": "M", "interval_text": "200-300 Druckstunden, b.B.", "cadence_days": None, "cadence_hours": 250, "sort_order": 150},
    {"id": "xl-fans", "applies_to": "xl5", "title": "XL Luefter reinigen", "details": "Toolhead- und Elektronikluefter reinigen, Rotorblaetter dabei festhalten.", "level": "M", "interval_text": "200-300 Druckstunden", "cadence_days": None, "cadence_hours": 250, "sort_order": 160},
    {"id": "xl-nextruders", "applies_to": "xl5", "title": "XL Nextruder und Filamentpfad reinigen", "details": "Alle fünf Nextruder auf Späne, Lauf und Förderung prüfen.", "level": "M", "interval_text": "200-300 Druckstunden, b.B.", "cadence_days": None, "cadence_hours": 250, "sort_order": 170},
    {"id": "xl-heaterblocks", "applies_to": "xl5", "title": "XL Heaterblocks reinigen", "details": "Kunststoffreste entfernen, Heiz-/Thermistorleitungen vorsichtig behandeln.", "level": "M", "interval_text": "200-300 Druckstunden, b.B.", "cadence_days": None, "cadence_hours": 250, "sort_order": 180},
    {"id": "xl-nozzle-position-tightening", "applies_to": "xl5", "title": "XL Nozzle-Position und Sitz prüfen", "details": "Alle fünf Nozzles/Hotends auf Position, Sitz und Verschleiß prüfen.", "level": "M", "interval_text": "200-300 Druckstunden, b.B.", "cadence_days": None, "cadence_hours": 250, "sort_order": 190},
    {"id": "xl-tool-1-nozzle", "applies_to": "xl5", "title": "XL Tool 1: Nozzle/Hotend", "details": "Nozzle-Wechsel, Cold Pull, Hotend-Auffälligkeiten und Material dokumentieren.", "level": "M", "interval_text": "b.B.", "cadence_days": None, "cadence_hours": None, "sort_order": 201},
    {"id": "xl-tool-2-nozzle", "applies_to": "xl5", "title": "XL Tool 2: Nozzle/Hotend", "details": "Nozzle-Wechsel, Cold Pull, Hotend-Auffälligkeiten und Material dokumentieren.", "level": "M", "interval_text": "b.B.", "cadence_days": None, "cadence_hours": None, "sort_order": 202},
    {"id": "xl-tool-3-nozzle", "applies_to": "xl5", "title": "XL Tool 3: Nozzle/Hotend", "details": "Nozzle-Wechsel, Cold Pull, Hotend-Auffälligkeiten und Material dokumentieren.", "level": "M", "interval_text": "b.B.", "cadence_days": None, "cadence_hours": None, "sort_order": 203},
    {"id": "xl-tool-4-nozzle", "applies_to": "xl5", "title": "XL Tool 4: Nozzle/Hotend", "details": "Nozzle-Wechsel, Cold Pull, Hotend-Auffälligkeiten und Material dokumentieren.", "level": "M", "interval_text": "b.B.", "cadence_days": None, "cadence_hours": None, "sort_order": 204},
    {"id": "xl-tool-5-nozzle", "applies_to": "xl5", "title": "XL Tool 5: Nozzle/Hotend", "details": "Nozzle-Wechsel, Cold Pull, Hotend-Auffälligkeiten und Material dokumentieren.", "level": "M", "interval_text": "b.B.", "cadence_days": None, "cadence_hours": None, "sort_order": 205},
    {"id": "xl-electronics", "applies_to": "xl5", "title": "XL Elektronik und Kabel prüfen", "details": "Stecker, Kabel, Elektronikgehäuse und Staub kontrollieren.", "level": "M", "interval_text": "600-800 Druckstunden", "cadence_days": None, "cadence_hours": 700, "sort_order": 210},
    {"id": "xl-toolchanger-couplers", "applies_to": "xl5", "title": "XL Toolchanger-Kupplungen reinigen/schmieren", "details": "Metallkontakte von ToolHead und ToolChanger reinigen/schmieren.", "level": "M", "interval_text": "mit Wartung oder b.B.", "cadence_days": None, "cadence_hours": 250, "sort_order": 220},
]
